version: "3.1"

services:
  indexhibit:
    build: .
    volumes:
      - ./www:/var/www/
    ports:
      - "9095:80"
    links:
      - "db:db"
  db:
    image: mysql:5.7.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "9091:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
